/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
	// Deletes ALL existing entries
	await knex("user_profile").del();

	// Inserts seed data
	await knex("user_profile").insert([
		{
			user_id: 1,
			net_worth: "$250,000",
			risk_tolerance: "High",
			trading_experience: "Advanced",
			products: JSON.stringify(["Stocks", "Bonds", "ETFs"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum", "Solana"]),
			current_occupation: "Software Engineer",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "No",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 2,
			net_worth: "$90,000",
			risk_tolerance: "Medium",
			trading_experience: "Intermediate",
			products: JSON.stringify(["Stocks", "Crypto"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Cardano", "Polkadot"]),
			current_occupation: "Marketing Manager",
			scammed_before: "Yes",
			someone_helping: "No",
			shared_access: "Yes",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 3,
			net_worth: "$500,000",
			risk_tolerance: "Low",
			trading_experience: "Beginner",
			products: JSON.stringify(["Stocks", "Real Estate"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum"]),
			current_occupation: "Real Estate Investor",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "No",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 4,
			net_worth: "$150,000",
			risk_tolerance: "Medium",
			trading_experience: "Intermediate",
			products: JSON.stringify(["Stocks", "ETFs"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Litecoin", "Dogecoin"]),
			current_occupation: "Product Manager",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "Yes",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 5,
			net_worth: "$80,000",
			risk_tolerance: "High",
			trading_experience: "Advanced",
			products: JSON.stringify(["Crypto", "Options"]),
			top_crypto_coins: JSON.stringify(["Ethereum", "Polkadot", "Chainlink"]),
			current_occupation: "Cryptocurrency Analyst",
			scammed_before: "Yes",
			someone_helping: "No",
			shared_access: "Yes",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 6,
			net_worth: "$1,000,000",
			risk_tolerance: "Low",
			trading_experience: "Intermediate",
			products: JSON.stringify(["Stocks", "Real Estate", "Bonds"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ripple", "Litecoin"]),
			current_occupation: "Financial Consultant",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "No",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 7,
			net_worth: "$200,000",
			risk_tolerance: "High",
			trading_experience: "Advanced",
			products: JSON.stringify(["Stocks", "Crypto", "Forex"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum", "Chainlink"]),
			current_occupation: "Entrepreneur",
			scammed_before: "Yes",
			someone_helping: "No",
			shared_access: "No",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 8,
			net_worth: "$300,000",
			risk_tolerance: "Medium",
			trading_experience: "Beginner",
			products: JSON.stringify(["Stocks", "Crypto"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum", "Solana"]),
			current_occupation: "Teacher",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "Yes",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 9,
			net_worth: "$75,000",
			risk_tolerance: "Low",
			trading_experience: "Beginner",
			products: JSON.stringify(["Stocks"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum"]),
			current_occupation: "Nurse",
			scammed_before: "No",
			someone_helping: "Yes",
			shared_access: "No",
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			user_id: 10,
			net_worth: "$350,000",
			risk_tolerance: "Medium",
			trading_experience: "Intermediate",
			products: JSON.stringify(["Real Estate", "ETFs"]),
			top_crypto_coins: JSON.stringify(["Bitcoin", "Ethereum", "Polkadot"]),
			current_occupation: "Civil Engineer",
			scammed_before: "Yes",
			someone_helping: "Yes",
			shared_access: "Yes",
			created_at: new Date(),
			updated_at: new Date(),
		},
	]);
}
